name: pingo_learn_r1
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  cloud_firestore: ^5.1.0
  firebase_remote_config: ^5.0.3
  flutter_screenutil: ^5.9.3
  provider: ^6.1.2
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.6.0
  fluttertoast: ^8.2.6
  retrofit: ^4.1.0
  dio: ^5.5.0+1
  redacted: ^1.0.11
  pretty_dio_logger: ^1.3.1
  connectivity_plus: ^6.0.3
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  infinite_scroll_pagination: ^4.0.0
  cached_network_image: ^3.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.5.2
  flutter_lints: ^3.0.0
  retrofit_generator: ^8.1.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/locales/
    - assets/lottie/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic




flutter_gen:
  output: lib/core/gen
  line_length: 80

  integrations:
    flutter_svg: false
    flare_flutter: false
    rive: false
    lottie: false

  colors:
    outputs:
      class_name: AppColors
    inputs:
      - assets/colors/colors.xml

  excluded_paths:
    - assets/fonts